import Head from 'next/head'
import React from 'react'
import { Nav, NavMobile } from '@/components/organisms'
import { ActionInfo } from '@/components/atoms'
import { useActionInfoStore } from '@/store/actionInfoStore'

interface LayoutProps {
  children: React.ReactNode
  title: string
}

export const Layout = ({
  children,
  title
}:LayoutProps) => {

  return (
    <>
    <Head>
      <title>{`${title} - Zounds`}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="flex relative">
      <Nav />
      <div className="max-h-screen min-h-screen w-full overflow-y-auto py-8 p-4 lg:p-8">
        <div className='mx-auto w-full max-w-screen-2xl flex flex-col gap-8 relative mb-40 md:mb-32 lg:mb-24'>
          {children}
        </div>
      </div>
      <ActionInfo />
      <NavMobile />
    </div>
  </>
  )
}
